spring.application.name=sunuagri-backend

# Connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sunuagri_db
spring.datasource.username=postgres
spring.datasource.password=zeynab

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Port du serveur (optionnel, 8080 par defaut)
server.port=8080